name: Hello Docker

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: [self-hosted]
    steps:
      - uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
  hello-world-ubi:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
